### ISSUE TITLE
是否考虑开发 MkDocs Plugin

### ISSUE THREAD

**Issue by jeremy-feng** [linyuxuanlin/Auto-i18n#2]
感谢作者开发这样一款高效的工具！不知作者是否考虑把本项目拓展成 MkDocs Plugin。用户可以通过 `pip install` 安装包，并在 `mkdocs.yml` 文件中配置一下，就能快速安装和使用。

- MkDocs 官方文档：https://www.mkdocs.org/dev-guide/plugins/#developing-plugins

- 一些很赞的 Plugin：https://github.com/mkdocs/catalog

**Comment by linyuxuanlin** [comment]
这个可以有！已加入后续的更新计划~
