### ISSUE TITLE
运行auto-translater.py报错呢

### ISSUE THREAD

**Issue by xingstarx** [linyuxuanlin/Auto-i18n#3]
感谢群友的好项目，非常有价值。

不过我还是碰到了一些问题。

我有过运行成功的经历，就是文章最终翻译为英文的，我有尝试过用自己的api_key 以及你推荐的那个网站的api_key，来运行这个项目，本地也设置过代理等等，转发openAi请求等。

不过我现在多次出现以下的错误，搞不懂为啥，大佬的代码没深究。这种问题我应该如何处理呢，是文章太长了么，或者说也可以打印详细的执行步骤的日志么.

```
An error has occurred: Invalid response object from API: 'An error occurred with this application.\n\nROUTER_EXTERNAL_TARGET_ERROR\n' (HTTP response code was 502)
```

**Comment by linyuxuanlin** [comment]
如果你有过成功运行的经历，那么本地的代码环境应该是没问题的。你可以尝试以下几种方法：

1. 使用第三方客户端（例如 ChatGPT Next Web）来测试你的 api key 是否可用。
2. 在 api url 后面加上 `/v1`，例如使用 `https://api.chatanywhere.com.cn/v1` 替换 `https://api.chatanywhere.com.cn`。
3. OpenAI 的服务有时候也会出问题的，不妨过两天再试试看。

**Comment by xingstarx** [comment]
经过这些天的使用心得，我觉得还真是你说的这些情况，一个是OpenAI 的服务器容易挂，一个是自己的代理服务器也容易挂，太坑了😂
